apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: custom-image-dev
  namespace: mq
spec:
  tasks:
    - name: git-clone-dev
      params:
        - name: GIT_SECRET
          value: "git-credentials"
        - name: GIT_SCRIPT
          value: "git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/IBMMQAutomation/base-image.git"
        - name: subdirectory
          value: "base-image"
        - name: source-dir
          value: /source
      taskRef:
        kind: Task
        name: git-clone-dev

    - name: build-dev
      params:
        - name: subdirectory
          value: "base-image"
        - name: source-dir
          value: /source
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/mq/pipeline-mq"
        - name: IMAGE_TAG
          value: "v2"
      taskRef:
        kind: Task
        name: build-dev
      runAfter:
        - git-clone-dev

    - name: smoke-test-dev
      params:
        - name: git-url
          value: "https://github.com/IBMMQAutomation/base-image.git"
        - name: git-clone
          value: git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/IBMMQAutomation/base-image.git
        - name: git-revision
          value: master
        - name: source-dir
          value: /source
        - name: image-server
          value: ""
        - name: image-namespace
          value: "mq"
        - name: image-repository
          value: ""
        - name: image-tag
          value: "v2"
        - name: app-namespace
          value: "mq"
        - name: app-name
          value: "qm1-smoke" # must be same as QM name https://github.com/IBMMQAutomation/base-image/blob/main/chart/base/values.yaml
        - name: deploy-ingress-type
          value: "route"
        - name: tools-image
          value: "quay.io/ibmgaragecloud/ibmcloud-dev:v2.0.4"
        - name: security
          value: "false"
        - name: ha
          value: "false"
        - name: subdirectory
          value: base-image
        - name: GIT_SECRET
          value: git-credentials
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/mq/pipeline-mq
      taskRef:
        kind: Task
        name: smoke-test-dev
      runAfter:
        - build-dev

    - name: cphtestp-performance-test-dev
      params:
        - name: git-url
          value: "https://github.com/IBMMQAutomation/base-image.git"
        - name: git-revision
          value: master
        - name: source-dir
          value: /source
        - name: subdirectory
          value: base-image
        - name: src-environment
          value: "mq"
        - name: test-plan
          value: ""
        - name: qm-security
          value: "false"
        - name: app-namespace
          value: "mq"
        - name: app-name
          value: "qm1-smoke"
      taskRef:
        kind: Task
        name: cphtestp-performance-test-dev
      runAfter:
        - smoke-test-dev

    - name: scan-dev
      params:
        - name: source-dir
          value: /source
        - name: BASE_IMAGE
          value: registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: subdirectory
          value: "base-image"
      taskRef:
        kind: Task
        name: scan-dev
      runAfter:
        - cphtestp-performance-test-dev

    - name: push-dev
      params:
        - name: subdirectory
          value: "base-image"
        - name: source-dir
          value: /source
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/mq/pipeline-mq"
        - name: IMAGE_TAG
          value: "v2"
      taskRef:
        kind: Task
        name: push-dev
      runAfter:
        - scan-dev
